# La clave de tu proyecto (la puedes ver en la URL de SonarCloud cuando entras a tu dashboard)
sonar.projectKey=JavierRodriguezPena_juice-shop
sonar.organization=javierrodriguezpena

# El nombre que se mostrará
sonar.projectName=Juice Shop PoC
sonar.projectVersion=1.0

# Dónde está el código a analizar
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/frontend/node_modules/**