name: DevSecOps CI/CD Pipeline

# Esto indica que el pipeline se lanzará automáticamente al hacer un push
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  SCA-Dependency-Check:
    name: OWASP Dependency Check (SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias de Node
        run: npm install --legacy-peer-deps
      
      - name: Ejecutar OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'JuiceShop'
          path: '.'
          format: 'HTML'
          args: >
            --exclude "**/test/**"
          
      - name: Subir reporte de vulnerabilidades
        uses: actions/upload-artifact@v4
        with:
          name: reporte-SCA
          path: reports/dependency-check-report.html

  SAST-SonarCloud:
    name: SonarCloud Scan (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para que SonarCloud lea el historial de Git
          
      - name: Ejecutar Análisis SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token nativo de GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # El secreto que configuraste