name: DevSecOps CI/CD Pipeline

# Esto indica que el pipeline se lanzará automáticamente al hacer un push
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  issues: write
  
jobs: 
  SCA-Dependency-Check:
    name: OWASP Dependency Check (SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias de Node
        run: npm install --legacy-peer-deps
      
      - name: Ejecutar OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'JuiceShop'
          path: '.'
          format: 'HTML'
          args: >
            --exclude "**/test/**"
            --failOnCVSS 7.0
          
      - name: Subir reporte de vulnerabilidades
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reporte-SCA
          path: reports/dependency-check-report.html

  SAST-SonarCloud:
    name: SonarCloud Scan (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para que SonarCloud lea el historial de Git
          
      - name: Ejecutar Análisis SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token nativo de GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # El secreto que configuraste
          
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  DAST-ZAP:
    name: OWASP ZAP Scan (DAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias de Node
        run: npm install --legacy-peer-deps

      - name: Levantar Juice Shop en segundo plano
        # El símbolo '&' al final es vital: hace que el servidor corra de fondo para que el pipeline pueda seguir al siguiente paso
        run: npm start &

      - name: Esperar a que la aplicación esté lista
        # Usamos wait-on para pausar el pipeline hasta que el puerto 3000 responda
        run: npx wait-on http://localhost:3000

      - name: Ejecutar OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          artifact_name: 'reporte-ZAP'
          # Dejamos esto en false temporalmente para que veas el reporte antes de aplicar la Quality Gate
          fail_action: false 

      - name: Subir reporte de ZAP
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reporte-DAST-ZAP
          path: report_html.html